// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:wird/data/models/app_settings.dart';
import 'package:wird/data/models/collection_selection.dart';
import 'package:wird/data/models/completion_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CollectionSelectionAdapter());
    registerAdapter(CompletionContentTypeAdapter());
    registerAdapter(CompletionEntryAdapter());
    registerAdapter(ThemeModePrefAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CollectionSelectionAdapter());
    registerAdapter(CompletionContentTypeAdapter());
    registerAdapter(CompletionEntryAdapter());
    registerAdapter(ThemeModePrefAdapter());
  }
}
